#!/bin/sh
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N nicaragua_mt
#$ -q omni
#$ -pe sm 1
#$ -P quanah
#$ -l h_rt=48:00:00
#$ -l h_vmem=8G
#$ -t 1-20


/lustre/work/jmanthey/bbmap/bbduk.sh in1=/lustre/scratch/johruska/nicaragua_honduras_pine_oak/nicaragua_honduras_pine_oak/renamed_raw_fastq/${SGE_TASK_ID}_R1.fastq.gz in2=/lustre/scratch/johruska/nicaragua_honduras_pine_oak/nicaragua_honduras_pine_oak/renamed_raw_fastq/${SGE_TASK_ID}_R2.fastq.gz out1=/lustre/scratch/johruska/nicaragua_honduras_pine_oak/nicaragua_honduras_pine_oak/cleaned_fastq/${SGE_TASK_ID}_R1.fastq.gz out2=/lustre/scratch/johruska/nicaragua_honduras_pine_oak/nicaragua_honduras_pine_oak/cleaned_fastq/${SGE_TASK_ID}_R2.fastq.gz minlen=50 ftl=10 qtrim=rl trimq=10 ktrim=r k=25 mink=7 ref=/lustre/work/jmanthey/bbmap/resources/adapters.fa hdist=1 tbo tpe

